baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'Cloudflare Gallery'

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"

[params]
  # Cloudflare Images configuration
  [params.cloudflareImages]
    accountHash = '' # Your Cloudflare account hash
    workerURL = '' # Your Cloudflare worker URL
    defaultLayout = 'grid'
    itemsPerPage = 30
    
    # Image variants
    variants = [
      { name = "thumbnail", width = 300, height = 300, fit = "cover" },
      { name = "preview", width = 800, height = 600, fit = "contain" },
      { name = "full", width = 2048, height = 0, fit = "contain" }
    ]
