name = 'cloudflare-gallery'
license = 'MIT'
licenselink = 'https://github.com/owner/repo/LICENSE'
description = 'A Hugo theme for creating beautiful image galleries using Cloudflare Images'

# The home page of the theme, where the source can be found

homepage = 'https://github.com/kimicla/cloudflare-gallery'

# If you have a running demo of the theme
demosite = 'https://kimicla.github.io/cloudflare-gallery'

# Taxonomy terms
tags = ['gallery', 'images', 'cloudflare', 'responsive', 'minimal']
features = [
    'Cloudflare Images integration',
    'Responsive grid layout',
    'Lazy loading',
    'Lightbox support',
    'Infinite scroll'
]

# If the theme has a single author
[author]
  name = 'Kimi Chen'
  homepage = 'http://kimi.qqviaja.com'

# Minimum Hugo version
[module.hugoVersion]
    extended = false
    min = "0.116.0"
